/**
 * @file services/slidesStorage.ts
 * @description Service to upload generated WebP slides and the manifest to Supabase Storage
 */

import { supabase } from "@/services/supabase/client";
import type { GeneratedSlide } from "@/features/admin/hooks/useSlideGeneration";

export async function uploadPresentation(
  slides: GeneratedSlide[],
  sessionId: string = "default"
): Promise<{ success: boolean; error?: string }> {
  if (!supabase) {
    return { success: false, error: "Supabase no está configurado" };
  }

  try {
    const uploadedSlides = [];
    let totalSize = 0;

    // Vérifier si le bucket existe (ou au moins tester la connexion au storage)
    const { data: buckets, error: bucketsError } = await supabase.storage.listBuckets();
    if (bucketsError) {
      console.warn("Could not list buckets (expected if no admin API key):", bucketsError.message);
    } else {
      const slidesBucket = buckets.find(b => b.name === "slides");
      if (!slidesBucket) {
        console.error("CRITICAL: Bucket 'slides' not found in Supabase Storage. Please create it.");
        return { success: false, error: "Le bucket 'slides' n'existe pas dans Supabase Storage." };
      }
    }

    // 1. Upload all WebP blobs
    for (let i = 0; i < slides.length; i++) {
      const slide = slides[i];
      if (!slide) continue;

      const fileName = `slide-${(i + 1).toString().padStart(3, "0")}.webp`;
      const filePath = `${sessionId}/${fileName}`;

      const { error } = await supabase.storage
        .from("slides")
        .upload(filePath, slide.blob, {
          contentType: "image/webp",
          upsert: true,
        });

      if (error) {
        console.error("Storage upload error details:", error);
        throw new Error(`Error uploading slide ${fileName}: ${error.message}`);
      }

      totalSize += slide.blob.size;
      
      uploadedSlides.push({
        index: i + 1,
        file: fileName,
        size: slide.blob.size,
        width: 1920, // default generated by pdf.js with scale 2.0 approx
        height: 1080 
      });
    }

    // 2. Generate and upload manifest
    const manifest = {
      version: "1.0",
      generatedAt: new Date().toISOString(),
      source: "destino-ia-pdf",
      settings: {
        quality: 80,
        maxWidth: 1920,
        dpi: 144
      },
      slides: uploadedSlides,
      totalSlides: slides.length,
      totalSize: totalSize
    };

    const manifestBlob = new Blob([JSON.stringify(manifest, null, 2)], {
      type: "application/json",
    });

    const { error: manifestError } = await supabase.storage
      .from("slides")
      .upload(`${sessionId}/slides-manifest.json`, manifestBlob, {
        contentType: "application/json",
        upsert: true,
      });

    if (manifestError) {
      console.error("Manifest upload error details:", manifestError);
      throw new Error(`Error uploading manifest: ${manifestError.message}`);
    }

    return { success: true };
  } catch (error) {
    return { 
      success: false, 
      error: error instanceof Error ? error.message : "Error desconocido" 
    };
  }
}

/**
 * Gets the public URL for the manifest
 */
export function getManifestUrl(sessionId: string = "default"): string | null {
  if (!supabase) return null;
  const { data } = supabase.storage.from("slides").getPublicUrl(`${sessionId}/slides-manifest.json`);
  return data.publicUrl;
}

/**
 * Gets the base public URL for slides folder
 */
export function getSlidesBaseUrl(sessionId: string = "default"): string | null {
  if (!supabase) return null;
  // Obtenemos la URL de un archivo ficticio para deducir la base
  const { data } = supabase.storage.from("slides").getPublicUrl(`${sessionId}/dummy.webp`);
  return data.publicUrl.replace("/dummy.webp", "");
}
